### ISSUE TITLE
[PARSE BUG]: signed_integral auto

### ISSUE THREAD

**Issue by virtuald** [robotpy/cxxheaderparser#103]
### Problem description

Some new concept thing maybe?

### C++ code that can't be parsed correctly (please double-check that https://robotpy.github.io/cxxheaderparser/ has the same error)

```text
constexpr std::signed_integral auto FloorDiv(std::signed_integral auto x,
                                             std::signed_integral auto y);
```

**Comment by auscompgeek** [comment]
https://en.cppreference.com/w/cpp/language/constraints
