### ISSUE TITLE
Parsing error for Standard_Real

### ISSUE THREAD

**Issue by trelau** [robotpy/cxxheaderparser#13]
When parsing:

```cpp
typedef void   Convert_CosAndSinEvalFunction(Standard_Real,
					     const Standard_Integer,
					     const TColgp_Array1OfPnt2d&,
					     const TColStd_Array1OfReal&,
					     const TColStd_Array1OfInteger*,
					     Standard_Real Result[2]) ;
```

`Standard_Real` is just a type in OpenCASCADE that is a double, I think.

**Comment by virtuald** [comment]
Oof, that's obnoxious. Simplified version is

```
typedef void fn(int);
```

Actual usage is something like this:

```

typedef void fntype(int);

void fn(int x) {

}

void test() {
    fntype* f = &fn;
}
```

Once again, another thing didn't realize you could do. I had been contemplating unifying FunctionType and Function, this would probably be a good motivator to actually do that.
