### ISSUE TITLE
Parsing error "evaluating '*': unexpected '*', expected ',' or ';'"

### ISSUE THREAD

**Issue by trelau** [robotpy/cxxheaderparser#33]
A few snippets from source header files below that cause the error:

```cpp
typedef void (GL_APIENTRY* PFNGLREADBUFFERPROC) (GLenum src);
```
and
```cpp
typedef const char* (WINAPI *wglGetExtensionsStringARB_t)(HDC theDeviceContext);
```

**Comment by virtuald** [comment]
This is a variation of #5.

Once #5 is addressed, you will need a preprocessor to translate `WINAPI` to `__stdcall`, etc.
