### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Bassoonian** [robotpy/cxxheaderparser#53]
### Problem description

cxxheaderparser is unable to deal with backslashes when used as a line continuation:
`cxxheaderparser.errors.CxxParseError: file.h:5: parse error evaluating '\': unexpected '\'`

### Operating System

MacOS

**Comment by virtuald** [comment]
Can you post the C++ code that can't be parsed?

**Comment by Bassoonian** [comment]
`#define CPU_FILL(value, dest, size, bit)                                          \
{                                                                                 \
    vu##bit tmp = (vu##bit)(value);                                               \
    CpuSet((void *)&tmp,                                                          \
           dest,                                                                  \
           CPU_SET_##bit##BIT | CPU_SET_SRC_FIXED | ((size)/(bit/8) & 0x1FFFFF)); \
}`

This is just one example.

**Comment by virtuald** [comment]
Those are C preprocessor macros. See the README:

> No C preprocessor substitution support implemented. If you are parsing headers that contain macros, you should preprocess your code using the excellent pure python preprocessor [pcpp](https://github.com/ned14/pcpp) or your favorite compiler

>  Included as an image because GitHub renders it unreadable.

If you surround with three tick marks (` ``` `), then it does a better job.
