### ISSUE TITLE
[PARSE BUG]: Line continuations are not considered

### ISSUE THREAD

**Issue by agatti** [robotpy/cxxheaderparser#54]
### Problem description

As per title, line continuations should make the parser skip all the following whitespace and consume the next token.

### C++ code that can't be parsed correctly (please double-check that https://robotpy.github.io/cxxheaderparser/ has the same error)

```text
static int \
                   variable;

#pragma (this \
        should \
        not \
        trigger \
        errors)
```

**Comment by virtuald** [comment]
Hm.

* GCC's preprocessor gets rid of the line continuations: https://godbolt.org/z/3co5z4ro3
* MSVC's preprocessor does not get rid of the line continuations: https://godbolt.org/z/aG6bMfMoE

It's likely this can be fixed by adjusting cxxheaderparser's lexer.
