### ISSUE TITLE
[PARSE BUG]: Falls over trying to parse a C bool shim

### ISSUE THREAD

**Issue by AlexMax** [robotpy/cxxheaderparser#55]
### Problem description

Trying to parse the header of [raylib.h](https://github.com/raysan5/raylib/blob/4.5.0/src/raylib.h) results in an error when it hits the bit that creates a `bool` enum for versions of C that don't have `stdbool.h`.

I have extracted a minimal repro from raylib and attached it.  The error for the below code is thus:
```
:5: parse error evaluating 'bool': unexpected 'bool'
```

### C++ code that can't be parsed correctly (please double-check that https://robotpy.github.io/cxxheaderparser/ has the same error)

```text
// Boolean type
#if (defined(__STDC__) && __STDC_VERSION__ >= 199901L) || (defined(_MSC_VER) && _MSC_VER >= 1800)
    #include <stdbool.h>
#elif !defined(__cplusplus) && !defined(bool)
    typedef enum bool { false = 0, true = !false } bool;
    #define RL_BOOL_TYPE
#endif
```

**Comment by virtuald** [comment]
This parser pretends to parse C++, not C, so when you preprocess that snippet `__cplusplus` should be defined and so the entire thing should be empty, which is not an error.
