### ISSUE TITLE
[PARSE BUG]: operator overloading with *

### ISSUE THREAD

**Issue by s33b00r** [robotpy/cxxheaderparser#57]
### Problem description

I got this parse error `parse error evaluating '*': unexpected '*', expected '('` when parsing some c++ code.
I think this is a problem with operator overloading over the `*` operator.

### C++ code that can't be parsed correctly (please double-check that https://robotpy.github.io/cxxheaderparser/ has the same error)

```text
operator const native_handle_t*() const
{
    return mHandle;
}
```

**Comment by virtuald** [comment]
Bug confirmed. Here's a complete example checked with godbolt for a testcase.

```c++

typedef int native_handle_t;

struct S {
  operator const native_handle_t*() const
  {
    return &m;
  }
  native_handle_t m;
};
```
