### ISSUE TITLE
[SUGGESTION]: parse doxygen comments

### ISSUE THREAD

**Issue by seladb** [robotpy/cxxheaderparser#76]
### Problem description

I'm not sure if it should be in the scope of this project, but parsing the doxygen comments could be nice, or at least support their command: https://www.doxygen.nl/manual/commands.html

This is probably a lot of work, but maybe we can start with basic commands? 🤔 

### Reproducible example code

```text
For example:


// t1.h

/**
 * \namespace my_namespace
 * \brief The main namespace for my project
 *
 * Some more details about this namespace
 */
namespace my_namespace
{
    ...
}


The output could be:
```json
{
  "namespaces": {
    "my_namespace": {
      "name": "my_namespace",
      "inline": false,
      "doxygen": {
        "brief": "The main namespace for my project",
        "description": "Some more details about this namespace",
      }
    }
  }
}
```
```

**Comment by virtuald** [comment]
It is out of scope -- but see https://github.com/auscompgeek/sphinxify which robotpy-build uses to do this same sort of thing. 

Probably makes sense to put this in the documentation somewhere.

**Comment by seladb** [comment]
Thanks for the reference, I'll take a look!
