### ISSUE TITLE
[PARSE BUG]:  function with trailing return type

### ISSUE THREAD

**Issue by scherno2000** [robotpy/cxxheaderparser#81]
### Problem description

**function with trailing return type having implementation won't parse**
parse error evaluating '{': unexpected '{'
auto test() -> void
{
}

the declaration parses correctly
auto test2() -> void;

ordinary return type having implementation parses
void test3()
{
}

I double checked  https://robotpy.github.io/cxxheaderparser/ has the same error

### C++ code that can't be parsed correctly (please double-check that https://robotpy.github.io/cxxheaderparser/ has the same error)

```text
auto test() -> void
{
}
```

**Comment by virtuald** [comment]
Thanks! Fixed and released as 1.2.1
