### ISSUE TITLE
Error for unexpected `operator`

### ISSUE THREAD

**Issue by trelau** [robotpy/cxxheaderparser#9]
Get error when parsing something like:

```cpp
class Foo
{

public:

operator SomeType () const { return SomeMethod(); }

};
```

**Comment by virtuald** [comment]
Heh, didn't realize you could do that. This one will be a bit more obnoxious to deal with, I might be able to get to it tomorrow night. There's a section of code that handles the special case of constructors (as they also don't have return values), and would need to be expanded to expect operator too.

Maybe comment it out and see if there are other parsing issues you run into for now?
