### ISSUE TITLE
[PARSE BUG]: C++14 single quote number separators are errors

### ISSUE THREAD

**Issue by guineawheek** [robotpy/cxxheaderparser#96]
### Problem description

Numeric literals in recent versions of C++ can be spaced with use of single quotes in the literal (e.g. `0xabcd'1234`), similar to how Python uses `_` in say `0x1234_5678`. These do not parse correctly and are treated like unmatched char literals.

### C++ code that can't be parsed correctly (please double-check that https://robotpy.github.io/cxxheaderparser/ has the same error)

```text
uint64_t value{0xffff'ffff};
```

**Comment by virtuald** [comment]
... why is that a thing? lol.
